// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dghezzwmzzfaqmoqdvdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnaGV6endtenpmYXFtb3FkdmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NjQ5MDksImV4cCI6MjA1NjI0MDkwOX0.GvM5C1Qlm9Gquk4eoQ-qWAOeTXb7vDX7hWUrRJVDInI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);